# Generated by Django 4.2.2 on 2023-06-18 08:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('description_one', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_avatar', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Info (eg: johndoe2@gmail.com)')),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Name (eg: twitter)')),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(blank=True, max_length=30, null=True, verbose_name='Greetings (eg: Hello)')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('par_inro', models.TextField(blank=True, null=True, verbose_name='Introduction')),
                ('avatar_img', models.CharField(blank=True, max_length=100, null=True)),
                ('hireMe_link', models.CharField(blank=True, max_length=200, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('lang_name', models.CharField(blank=True, max_length=100, verbose_name='Language Name')),
                ('exp_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=200, verbose_name='Experience Level')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language_used', models.CharField(blank=True, max_length=100, null=True)),
                ('about_avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('Project_info', models.TextField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.CharField(blank=True, max_length=100, null=True)),
                ('service_name', models.CharField(blank=True, max_length=40, null=True)),
                ('shadow_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('social_icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
